swagger: "2.0"
info:
  version: "0.0.1"
  title: Nena
# during dev, should point to your local machine
host: localhost:9001
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  #Coin routes
  /call-center:
    # binds a127 app logic to a route (controller)
    x-swagger-router-controller: voice
    post:
      tags:
        - CallCenter
      summary: Call center
      description: Call support center. Routes calls to available numbers.
      consumes:
        - 'application/x-www-form-urlencoded'
        - 'application/json'
      produces:
        - 'text/plain'
      operationId: callCenter
      responses:
        "200":
          description: Success

  /call:
    # binds a127 app logic to a route (controller)
    x-swagger-router-controller: voice
    post:
      tags:
        - Call
      summary: Call
      description: Call a given phone number
      operationId: call
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/VoiceResponse"
        # responses may fall through to errors
        "400":
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /swagger:
    x-swagger-pipe: swagger_raw

# complex objects have schema definitions. Responses and error messages
definitions:
  #socket definitions
  VoiceResponse:
    properties:
      message:
        type: string

  # Default error response
  ErrorResponse:
    type: object
    properties:
      errors:
        type: array
        items: 
          type: object